apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tls-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: ctrl.iulian.cld
      tls:
        certificateRefs:
          - kind: Secret
            name: grpc-certificate
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpc-route
spec:
  parentRefs:
    - name: tls-gateway
  rules:
    - backendRefs:
        - name: grpc-echo
          port: 50051
