apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hyperdx-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-vault
    kind: ClusterSecretStore
  target:
    name: hyperdx-secret
    creationPolicy: Owner
  data:
    - secretKey: clickhouse
      remoteRef:
        key: /dev/config
        property: clickhouse
