apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:iuliansafta/iulian-cloud-gitops.git
    targetRevision: HEAD
    path: apps/homelab-1/cilium-test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
