apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:iuliansafta/iulian-cloud-gitops.git
    targetRevision: HEAD
    path: apps/homelab-1/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: default
