apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io/
      targetRevision: v1.0.0

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
